# Generated by Django 2.0 on 2018-02-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    atomic=False
    dependencies = [
        ('posts', '0004_auto_20180215_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
