# Generated by Django 2.0 on 2018-02-19 13:43

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180219_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_c',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_uploads_path),
        ),
    ]
